### ISSUE TITLE
GETとPOSTが同時にされるとエラーが出る問題

### ISSUE THREAD

**Issue by bieshan** [kinc-shinshu/solena#11]
### 問題点
POSTとGETが同時起きるとエラー出て落ちる。

### 原因
おそらくGETでの操作とPOSTでの操作で同じ`key`に対して書き込みをしているため、
エラーが起きたと思われる。

### 解決方法
 - Redisのpub/subを利用するか
 - GETとPOSTのリクエストをキューに入れるようにするか
 - エラー処理を行って、落ちないようにする

**Comment by arsley** [comment]
`use of closed network connection`

https://stackoverflow.com/questions/34180858/setex-error-use-of-closed-network-connection
